/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    accounts: AccountAuthOperations;
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    classes: Class;
    chapters: Chapter;
    lessons: Lesson;
    pages: Page;
    classrooms: Classroom;
    'classroom-memberships': ClassroomMembership;
    organizations: Organization;
    'reporting-periods': ReportingPeriod;
    'rppr-reports': RpprReport;
    'reporting-snapshots': ReportingSnapshot;
    'reporting-audit-events': ReportingAuditEvent;
    'reporting-saved-views': ReportingSavedView;
    'reporting-evidence-links': ReportingEvidenceLink;
    'reporting-product-records': ReportingProductRecord;
    accounts: Account;
    users: User;
    media: Media;
    questions: Question;
    'quiz-questions': QuizQuestion;
    quizzes: Quiz;
    'quiz-attempts': QuizAttempt;
    notifications: Notification;
    'lesson-progress': LessonProgress;
    'lesson-bookmarks': LessonBookmark;
    feedback: Feedback;
    'lesson-feedback': LessonFeedback;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    classes: ClassesSelect<false> | ClassesSelect<true>;
    chapters: ChaptersSelect<false> | ChaptersSelect<true>;
    lessons: LessonsSelect<false> | LessonsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    classrooms: ClassroomsSelect<false> | ClassroomsSelect<true>;
    'classroom-memberships': ClassroomMembershipsSelect<false> | ClassroomMembershipsSelect<true>;
    organizations: OrganizationsSelect<false> | OrganizationsSelect<true>;
    'reporting-periods': ReportingPeriodsSelect<false> | ReportingPeriodsSelect<true>;
    'rppr-reports': RpprReportsSelect<false> | RpprReportsSelect<true>;
    'reporting-snapshots': ReportingSnapshotsSelect<false> | ReportingSnapshotsSelect<true>;
    'reporting-audit-events': ReportingAuditEventsSelect<false> | ReportingAuditEventsSelect<true>;
    'reporting-saved-views': ReportingSavedViewsSelect<false> | ReportingSavedViewsSelect<true>;
    'reporting-evidence-links': ReportingEvidenceLinksSelect<false> | ReportingEvidenceLinksSelect<true>;
    'reporting-product-records': ReportingProductRecordsSelect<false> | ReportingProductRecordsSelect<true>;
    accounts: AccountsSelect<false> | AccountsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    questions: QuestionsSelect<false> | QuestionsSelect<true>;
    'quiz-questions': QuizQuestionsSelect<false> | QuizQuestionsSelect<true>;
    quizzes: QuizzesSelect<false> | QuizzesSelect<true>;
    'quiz-attempts': QuizAttemptsSelect<false> | QuizAttemptsSelect<true>;
    notifications: NotificationsSelect<false> | NotificationsSelect<true>;
    'lesson-progress': LessonProgressSelect<false> | LessonProgressSelect<true>;
    'lesson-bookmarks': LessonBookmarksSelect<false> | LessonBookmarksSelect<true>;
    feedback: FeedbackSelect<false> | FeedbackSelect<true>;
    'lesson-feedback': LessonFeedbackSelect<false> | LessonFeedbackSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'admin-help': AdminHelp;
    footer: Footer;
    'site-branding': SiteBranding;
  };
  globalsSelect: {
    'admin-help': AdminHelpSelect<false> | AdminHelpSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    'site-branding': SiteBrandingSelect<false> | SiteBrandingSelect<true>;
  };
  locale: null;
  user:
    | (Account & {
        collection: 'accounts';
      })
    | (User & {
        collection: 'users';
      });
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface AccountAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "classes".
 */
export interface Class {
  id: number;
  title: string;
  description?: string | null;
  order?: number | null;
  chapters?: (number | Chapter)[] | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "chapters".
 */
export interface Chapter {
  id: number;
  title: string;
  /**
   * Shown as Ch {number} in the sidebar.
   */
  chapterNumber?: number | null;
  lessons?: (number | Lesson)[] | null;
  class: number | Class;
  slug: string;
  /**
   * Use $...$ for inline math and $$...$$ for display math.
   */
  objective?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lessons".
 */
export interface Lesson {
  id: number;
  /**
   * Managed from the Reorder lessons list.
   */
  order?: number | null;
  title: string;
  /**
   * Assign this lesson to a chapter.
   */
  chapter: number | Chapter;
  /**
   * Auto-generated from the lesson title. Must be unique within a chapter.
   */
  slug: string;
  /**
   * Build the lesson by adding and reordering content blocks.
   */
  layout?:
    | (
        | {
            title: string;
            subtitle?: string | null;
            buttonLabel?: string | null;
            buttonHref?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'heroBlock';
          }
        | {
            title: string;
            subtitle?: string | null;
            size?: ('sm' | 'md' | 'lg') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'sectionTitle';
          }
        | {
            title: string;
            text?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            size?: ('sm' | 'md' | 'lg') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'sectionBlock';
          }
        | {
            body: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'richTextBlock';
          }
        | {
            text?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textBlock';
          }
        | {
            video?: (number | null) | Media;
            url?: string | null;
            caption?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'videoBlock';
          }
        | {
            title?: string | null;
            listStyle?: ('unordered' | 'ordered') | null;
            items?:
              | {
                  text?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'listBlock';
          }
        | {
            title?: string | null;
            steps?:
              | {
                  heading: string;
                  description?: {
                    root: {
                      type: string;
                      children: {
                        type: any;
                        version: number;
                        [k: string]: unknown;
                      }[];
                      direction: ('ltr' | 'rtl') | null;
                      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                      indent: number;
                      version: number;
                    };
                    [k: string]: unknown;
                  } | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'stepsList';
          }
        | {
            label: string;
            href: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'buttonBlock';
          }
        | {
            title?: string | null;
            description?: string | null;
            resources?:
              | {
                  title: string;
                  description?: string | null;
                  url: string;
                  type?: ('link' | 'video' | 'download' | 'other') | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'resourcesList';
          }
        | {
            title?: string | null;
            description?: string | null;
            groupByCategory?: boolean | null;
            contacts?:
              | {
                  name: string;
                  title?: string | null;
                  category?: ('staff' | 'technical') | null;
                  phone?: string | null;
                  email?: string | null;
                  photo?: (number | null) | Media;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'contactsList';
          }
        | {
            title?: string | null;
            quiz: number | Quiz;
            showTitle?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'quizBlock';
          }
      )[]
    | null;
  assessment?: {
    /**
     * Attach a quiz to this lesson or create a new one.
     */
    quiz?: (number | null) | Quiz;
    showAnswers?: boolean | null;
    /**
     * Leave blank for unlimited attempts.
     */
    maxAttempts?: number | null;
    /**
     * Overrides the quiz time limit for this lesson if set.
     */
    timeLimitSec?: number | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quizzes".
 */
export interface Quiz {
  id: number;
  title: string;
  description?: string | null;
  /**
   * Optional. Used for filtering in the Quiz Bank.
   */
  course?: (number | null) | Class;
  /**
   * Optional. Used for filtering in the Quiz Bank.
   */
  chapter?: (number | null) | Chapter;
  tags?: string[] | null;
  difficulty?: ('intro' | 'easy' | 'medium' | 'hard') | null;
  /**
   * Add questions from the bank or create new ones.
   */
  questions: (number | QuizQuestion)[];
  shuffleQuestions?: boolean | null;
  shuffleOptions?: boolean | null;
  scoring?: ('per-question' | 'all-or-nothing' | 'partial') | null;
  timeLimitSec?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quiz-questions".
 */
export interface QuizQuestion {
  id: number;
  title: string;
  prompt: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  options: {
    label: string;
    isCorrect?: boolean | null;
    id?: string | null;
  }[];
  explanation?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  attachments?: (number | Media)[] | null;
  topic?: string | null;
  tags?: string[] | null;
  difficulty?: ('intro' | 'easy' | 'medium' | 'hard') | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  /**
   * Managed from the Reorder pages list.
   */
  navOrder?: number | null;
  title: string;
  /**
   * Auto-generated from the page title. Use 'Home' to create the homepage slug.
   */
  slug: string;
  /**
   * Build the page by adding and reordering content blocks.
   */
  layout?:
    | (
        | {
            title: string;
            subtitle?: string | null;
            buttonLabel?: string | null;
            buttonHref?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'heroBlock';
          }
        | {
            title: string;
            subtitle?: string | null;
            size?: ('sm' | 'md' | 'lg') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'sectionTitle';
          }
        | {
            title: string;
            text?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            size?: ('sm' | 'md' | 'lg') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'sectionBlock';
          }
        | {
            body: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'richTextBlock';
          }
        | {
            text?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textBlock';
          }
        | {
            video?: (number | null) | Media;
            url?: string | null;
            caption?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'videoBlock';
          }
        | {
            title?: string | null;
            listStyle?: ('unordered' | 'ordered') | null;
            items?:
              | {
                  text?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'listBlock';
          }
        | {
            title?: string | null;
            steps?:
              | {
                  heading: string;
                  description?: {
                    root: {
                      type: string;
                      children: {
                        type: any;
                        version: number;
                        [k: string]: unknown;
                      }[];
                      direction: ('ltr' | 'rtl') | null;
                      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                      indent: number;
                      version: number;
                    };
                    [k: string]: unknown;
                  } | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'stepsList';
          }
        | {
            label: string;
            href: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'buttonBlock';
          }
        | {
            title?: string | null;
            description?: string | null;
            resources?:
              | {
                  title: string;
                  description?: string | null;
                  url: string;
                  type?: ('link' | 'video' | 'download' | 'other') | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'resourcesList';
          }
        | {
            title?: string | null;
            description?: string | null;
            groupByCategory?: boolean | null;
            contacts?:
              | {
                  name: string;
                  title?: string | null;
                  category?: ('staff' | 'technical') | null;
                  phone?: string | null;
                  email?: string | null;
                  photo?: (number | null) | Media;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'contactsList';
          }
        | {
            title?: string | null;
            quiz: number | Quiz;
            showTitle?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'quizBlock';
          }
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "classrooms".
 */
export interface Classroom {
  id: number;
  title: string;
  class: number | Class;
  professor: number | User;
  /**
   * Share this code with students to join the classroom.
   */
  joinCode: string;
  /**
   * Controls the length of newly generated join codes.
   */
  joinCodeLength?: number | null;
  /**
   * How long new join codes remain valid.
   */
  joinCodeDurationHours?: number | null;
  joinCodeExpiresAt?: string | null;
  joinCodeLastRotatedAt?: string | null;
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  firstName?: string | null;
  lastName?: string | null;
  /**
   * Syncs with the theme toggle in the admin UI.
   */
  adminTheme?: ('light' | 'dark') | null;
  /**
   * Admins can manage users, settings, and the entire CMS. Staff can edit content only.
   */
  role: 'admin' | 'professor' | 'staff';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "classroom-memberships".
 */
export interface ClassroomMembership {
  id: number;
  classroom: number | Classroom;
  student: number | Account;
  joinedAt?: string | null;
  totalLessons?: number | null;
  completedLessons?: number | null;
  /**
   * Completed lessons divided by lessons started.
   */
  completionRate?: number | null;
  lastActivityAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "accounts".
 */
export interface Account {
  id: number;
  emailVerified?: boolean | null;
  emailVerifiedAt?: string | null;
  emailVerificationTokenHash?: string | null;
  emailVerificationExpiresAt?: string | null;
  /**
   * Student role for learner accounts.
   */
  role: 'student';
  fullName?: string | null;
  currentStreak?: number | null;
  longestStreak?: number | null;
  lastStreakDate?: string | null;
  /**
   * Used for NSF participant reporting exports.
   */
  participantType?:
    | ('undergraduate_student' | 'graduate_student' | 'k12_student' | 'teacher' | 'staff' | 'faculty' | 'other')
    | null;
  /**
   * RPPR participant role in this project.
   */
  projectRole?: string | null;
  organization?: (number | null) | Organization;
  /**
   * Optional reporting snapshot for exports when the organization relationship is empty.
   */
  organizationName?: string | null;
  /**
   * Summary of participant contributions used in RPPR narratives.
   */
  contributionSummary?: string | null;
  participationStartDate?: string | null;
  participationEndDate?: string | null;
  /**
   * Supports cohort filtering in reporting center.
   */
  firstGenCollegeStudent?: boolean | null;
  /**
   * Supports cohort filtering in reporting center.
   */
  transferStudent?: boolean | null;
  includeInRppr?: boolean | null;
  /**
   * Reserved for CPP SSO integration (e.g., Okta, Azure AD).
   */
  ssoProvider?: string | null;
  /**
   * Reserved for CPP SSO integration (unique external user id).
   */
  ssoSubject?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "organizations".
 */
export interface Organization {
  id: number;
  organizationName: string;
  organizationType?: ('academic' | 'industry' | 'nonprofit' | 'government' | 'school_district' | 'other') | null;
  /**
   * Role this organization plays in the project (e.g., curriculum partner).
   */
  partnerRole?: string | null;
  contributionSummary?: string | null;
  contactName?: string | null;
  contactEmail?: string | null;
  website?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reporting-periods".
 */
export interface ReportingPeriod {
  id: number;
  label: string;
  /**
   * Optional award budget period label.
   */
  budgetPeriodName?: string | null;
  reportType: 'annual' | 'final' | 'internal' | 'custom';
  startDate: string;
  endDate: string;
  status?: ('draft' | 'active' | 'archived') | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rppr-reports".
 */
export interface RpprReport {
  id: number;
  title: string;
  reportingPeriod?: (number | null) | ReportingPeriod;
  reportType: 'annual' | 'final' | 'internal' | 'custom';
  startDate: string;
  endDate: string;
  accomplishmentsNarrative?: string | null;
  productsNarrative?: string | null;
  impactNarrative?: string | null;
  changesProblemsNarrative?: string | null;
  specialRequirementsNarrative?: string | null;
  reportNotes?: string | null;
  attachments?: (number | Media)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reporting-snapshots".
 */
export interface ReportingSnapshot {
  id: number;
  label: string;
  reportType: 'annual' | 'final' | 'internal' | 'custom';
  reportingPeriod?: (number | null) | ReportingPeriod;
  periodStart: string;
  periodEnd: string;
  filterScope:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  metricPayload:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  rpprPayload?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  dataQualityPayload?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  anomaliesPayload?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  narrativeDrafts?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  snapshotHash: string;
  reproducibilityKey: string;
  versionLabel: string;
  createdBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reporting-audit-events".
 */
export interface ReportingAuditEvent {
  id: number;
  eventType:
    | 'report_generated'
    | 'snapshot_created'
    | 'snapshot_reused'
    | 'export_generated'
    | 'drilldown_viewed'
    | 'saved_view_created';
  reportType?: ('annual' | 'final' | 'internal' | 'custom') | null;
  reportingPeriod?: (number | null) | ReportingPeriod;
  periodStart?: string | null;
  periodEnd?: string | null;
  filters?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  exportType?: string | null;
  exportFormat?: string | null;
  metricKey?: string | null;
  snapshot?: (number | null) | ReportingSnapshot;
  notes?: string | null;
  createdBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reporting-saved-views".
 */
export interface ReportingSavedView {
  id: number;
  label: string;
  owner: number | User;
  isShared?: boolean | null;
  reportType?: ('annual' | 'final' | 'internal' | 'custom') | null;
  reportingPeriod?: (number | null) | ReportingPeriod;
  startDate?: string | null;
  endDate?: string | null;
  filters:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  metricKeys?:
    | {
        metricKey: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reporting-evidence-links".
 */
export interface ReportingEvidenceLink {
  id: number;
  title: string;
  evidenceType: 'curriculum_change' | 'intervention' | 'product_resource' | 'publication' | 'other';
  rpprSection:
    | 'accomplishments'
    | 'products'
    | 'participantsOrganizations'
    | 'impact'
    | 'changesProblems'
    | 'specialRequirements';
  summary?: string | null;
  impactNote?: string | null;
  reportingPeriod?: (number | null) | ReportingPeriod;
  linkedArtifacts?:
    | (
        | {
            relationTo: 'classes';
            value: number | Class;
          }
        | {
            relationTo: 'lessons';
            value: number | Lesson;
          }
        | {
            relationTo: 'quizzes';
            value: number | Quiz;
          }
        | {
            relationTo: 'pages';
            value: number | Page;
          }
        | {
            relationTo: 'quiz-questions';
            value: number | QuizQuestion;
          }
      )[]
    | null;
  linkedSnapshot?: (number | null) | ReportingSnapshot;
  linkedRpprReport?: (number | null) | RpprReport;
  occurredAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reporting-product-records".
 */
export interface ReportingProductRecord {
  id: number;
  title: string;
  productType: 'publication' | 'patent' | 'dataset' | 'software' | 'educational_material' | 'other';
  /**
   * Formal citation or product description used for RPPR products section.
   */
  citation?: string | null;
  /**
   * DOI, patent number, accession ID, or other stable identifier.
   */
  identifier?: string | null;
  /**
   * Public URL where the product can be reviewed.
   */
  url?: string | null;
  reportingPeriod?: (number | null) | ReportingPeriod;
  linkedRpprReport?: (number | null) | RpprReport;
  linkedArtifacts?:
    | (
        | {
            relationTo: 'classes';
            value: number | Class;
          }
        | {
            relationTo: 'lessons';
            value: number | Lesson;
          }
        | {
            relationTo: 'quizzes';
            value: number | Quiz;
          }
        | {
            relationTo: 'pages';
            value: number | Page;
          }
        | {
            relationTo: 'quiz-questions';
            value: number | QuizQuestion;
          }
      )[]
    | null;
  reportedAt?: string | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "questions".
 */
export interface Question {
  id: number;
  user: number | Account;
  /**
   * Question is scoped to this lesson.
   */
  lesson: number | Lesson;
  chapter?: (number | null) | Chapter;
  class?: (number | null) | Class;
  status: 'open' | 'answered' | 'resolved';
  title: string;
  /**
   * Use Markdown or simple text. Math with $...$ is supported on the frontend.
   */
  body: string;
  attachment?: (number | null) | Media;
  /**
   * Staff and TAs can respond here.
   */
  answers?:
    | {
        author: number | User;
        body: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        createdAt: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quiz-attempts".
 */
export interface QuizAttempt {
  id: number;
  quiz: number | Quiz;
  lesson?: (number | null) | Lesson;
  user: number | Account;
  startedAt?: string | null;
  completedAt?: string | null;
  durationSec?: number | null;
  questionOrder?:
    | {
        question: number | QuizQuestion;
        id?: string | null;
      }[]
    | null;
  answers?:
    | {
        question: number | QuizQuestion;
        selectedOptionIds?:
          | {
              optionId?: string | null;
              id?: string | null;
            }[]
          | null;
        optionOrder?:
          | {
              optionId?: string | null;
              id?: string | null;
            }[]
          | null;
        isCorrect?: boolean | null;
        score?: number | null;
        id?: string | null;
      }[]
    | null;
  score?: number | null;
  maxScore?: number | null;
  correctCount?: number | null;
  questionCount?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications".
 */
export interface Notification {
  id: number;
  recipient: number | Account;
  type: 'question_answered' | 'new_content' | 'announcement' | 'quiz_deadline';
  title: string;
  body?: string | null;
  /**
   * Optional URL the student is taken to when clicking this notification.
   */
  link?: string | null;
  question?: (number | null) | Question;
  read?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lesson-progress".
 */
export interface LessonProgress {
  id: number;
  user: number | Account;
  lesson: number | Lesson;
  chapter?: (number | null) | Chapter;
  class?: (number | null) | Class;
  completed?: boolean | null;
  completedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lesson-bookmarks".
 */
export interface LessonBookmark {
  id: number;
  user: number | Account;
  lesson: number | Lesson;
  chapter?: (number | null) | Chapter;
  class?: (number | null) | Class;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "feedback".
 */
export interface Feedback {
  id: number;
  email?: string | null;
  read?: boolean | null;
  message: string;
  pageUrl?: string | null;
  userAgent?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lesson-feedback".
 */
export interface LessonFeedback {
  id: number;
  user?: (number | null) | Account;
  /**
   * Feedback is scoped to this lesson.
   */
  lesson: number | Lesson;
  chapter?: (number | null) | Chapter;
  class?: (number | null) | Class;
  rating: 'not_helpful' | 'somewhat_helpful' | 'helpful' | 'very_helpful';
  /**
   * Optional comments from the student.
   */
  message?: string | null;
  /**
   * Staff reply shown in the admin panel.
   */
  reply?: string | null;
  repliedAt?: string | null;
  repliedBy?: (number | null) | User;
  pageUrl?: string | null;
  userAgent?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'classes';
        value: number | Class;
      } | null)
    | ({
        relationTo: 'chapters';
        value: number | Chapter;
      } | null)
    | ({
        relationTo: 'lessons';
        value: number | Lesson;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'classrooms';
        value: number | Classroom;
      } | null)
    | ({
        relationTo: 'classroom-memberships';
        value: number | ClassroomMembership;
      } | null)
    | ({
        relationTo: 'organizations';
        value: number | Organization;
      } | null)
    | ({
        relationTo: 'reporting-periods';
        value: number | ReportingPeriod;
      } | null)
    | ({
        relationTo: 'rppr-reports';
        value: number | RpprReport;
      } | null)
    | ({
        relationTo: 'reporting-snapshots';
        value: number | ReportingSnapshot;
      } | null)
    | ({
        relationTo: 'reporting-audit-events';
        value: number | ReportingAuditEvent;
      } | null)
    | ({
        relationTo: 'reporting-saved-views';
        value: number | ReportingSavedView;
      } | null)
    | ({
        relationTo: 'reporting-evidence-links';
        value: number | ReportingEvidenceLink;
      } | null)
    | ({
        relationTo: 'reporting-product-records';
        value: number | ReportingProductRecord;
      } | null)
    | ({
        relationTo: 'accounts';
        value: number | Account;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'questions';
        value: number | Question;
      } | null)
    | ({
        relationTo: 'quiz-questions';
        value: number | QuizQuestion;
      } | null)
    | ({
        relationTo: 'quizzes';
        value: number | Quiz;
      } | null)
    | ({
        relationTo: 'quiz-attempts';
        value: number | QuizAttempt;
      } | null)
    | ({
        relationTo: 'notifications';
        value: number | Notification;
      } | null)
    | ({
        relationTo: 'lesson-progress';
        value: number | LessonProgress;
      } | null)
    | ({
        relationTo: 'lesson-bookmarks';
        value: number | LessonBookmark;
      } | null)
    | ({
        relationTo: 'feedback';
        value: number | Feedback;
      } | null)
    | ({
        relationTo: 'lesson-feedback';
        value: number | LessonFeedback;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'accounts';
        value: number | Account;
      }
    | {
        relationTo: 'users';
        value: number | User;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user:
    | {
        relationTo: 'accounts';
        value: number | Account;
      }
    | {
        relationTo: 'users';
        value: number | User;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "classes_select".
 */
export interface ClassesSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  order?: T;
  chapters?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "chapters_select".
 */
export interface ChaptersSelect<T extends boolean = true> {
  title?: T;
  chapterNumber?: T;
  lessons?: T;
  class?: T;
  slug?: T;
  objective?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lessons_select".
 */
export interface LessonsSelect<T extends boolean = true> {
  order?: T;
  title?: T;
  chapter?: T;
  slug?: T;
  layout?:
    | T
    | {
        heroBlock?:
          | T
          | {
              title?: T;
              subtitle?: T;
              buttonLabel?: T;
              buttonHref?: T;
              id?: T;
              blockName?: T;
            };
        sectionTitle?:
          | T
          | {
              title?: T;
              subtitle?: T;
              size?: T;
              id?: T;
              blockName?: T;
            };
        sectionBlock?:
          | T
          | {
              title?: T;
              text?: T;
              size?: T;
              id?: T;
              blockName?: T;
            };
        richTextBlock?:
          | T
          | {
              body?: T;
              id?: T;
              blockName?: T;
            };
        textBlock?:
          | T
          | {
              text?: T;
              id?: T;
              blockName?: T;
            };
        videoBlock?:
          | T
          | {
              video?: T;
              url?: T;
              caption?: T;
              id?: T;
              blockName?: T;
            };
        listBlock?:
          | T
          | {
              title?: T;
              listStyle?: T;
              items?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        stepsList?:
          | T
          | {
              title?: T;
              steps?:
                | T
                | {
                    heading?: T;
                    description?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        buttonBlock?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
              blockName?: T;
            };
        resourcesList?:
          | T
          | {
              title?: T;
              description?: T;
              resources?:
                | T
                | {
                    title?: T;
                    description?: T;
                    url?: T;
                    type?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        contactsList?:
          | T
          | {
              title?: T;
              description?: T;
              groupByCategory?: T;
              contacts?:
                | T
                | {
                    name?: T;
                    title?: T;
                    category?: T;
                    phone?: T;
                    email?: T;
                    photo?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        quizBlock?:
          | T
          | {
              title?: T;
              quiz?: T;
              showTitle?: T;
              id?: T;
              blockName?: T;
            };
      };
  assessment?:
    | T
    | {
        quiz?: T;
        showAnswers?: T;
        maxAttempts?: T;
        timeLimitSec?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  navOrder?: T;
  title?: T;
  slug?: T;
  layout?:
    | T
    | {
        heroBlock?:
          | T
          | {
              title?: T;
              subtitle?: T;
              buttonLabel?: T;
              buttonHref?: T;
              id?: T;
              blockName?: T;
            };
        sectionTitle?:
          | T
          | {
              title?: T;
              subtitle?: T;
              size?: T;
              id?: T;
              blockName?: T;
            };
        sectionBlock?:
          | T
          | {
              title?: T;
              text?: T;
              size?: T;
              id?: T;
              blockName?: T;
            };
        richTextBlock?:
          | T
          | {
              body?: T;
              id?: T;
              blockName?: T;
            };
        textBlock?:
          | T
          | {
              text?: T;
              id?: T;
              blockName?: T;
            };
        videoBlock?:
          | T
          | {
              video?: T;
              url?: T;
              caption?: T;
              id?: T;
              blockName?: T;
            };
        listBlock?:
          | T
          | {
              title?: T;
              listStyle?: T;
              items?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        stepsList?:
          | T
          | {
              title?: T;
              steps?:
                | T
                | {
                    heading?: T;
                    description?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        buttonBlock?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
              blockName?: T;
            };
        resourcesList?:
          | T
          | {
              title?: T;
              description?: T;
              resources?:
                | T
                | {
                    title?: T;
                    description?: T;
                    url?: T;
                    type?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        contactsList?:
          | T
          | {
              title?: T;
              description?: T;
              groupByCategory?: T;
              contacts?:
                | T
                | {
                    name?: T;
                    title?: T;
                    category?: T;
                    phone?: T;
                    email?: T;
                    photo?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        quizBlock?:
          | T
          | {
              title?: T;
              quiz?: T;
              showTitle?: T;
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "classrooms_select".
 */
export interface ClassroomsSelect<T extends boolean = true> {
  title?: T;
  class?: T;
  professor?: T;
  joinCode?: T;
  joinCodeLength?: T;
  joinCodeDurationHours?: T;
  joinCodeExpiresAt?: T;
  joinCodeLastRotatedAt?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "classroom-memberships_select".
 */
export interface ClassroomMembershipsSelect<T extends boolean = true> {
  classroom?: T;
  student?: T;
  joinedAt?: T;
  totalLessons?: T;
  completedLessons?: T;
  completionRate?: T;
  lastActivityAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "organizations_select".
 */
export interface OrganizationsSelect<T extends boolean = true> {
  organizationName?: T;
  organizationType?: T;
  partnerRole?: T;
  contributionSummary?: T;
  contactName?: T;
  contactEmail?: T;
  website?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reporting-periods_select".
 */
export interface ReportingPeriodsSelect<T extends boolean = true> {
  label?: T;
  budgetPeriodName?: T;
  reportType?: T;
  startDate?: T;
  endDate?: T;
  status?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rppr-reports_select".
 */
export interface RpprReportsSelect<T extends boolean = true> {
  title?: T;
  reportingPeriod?: T;
  reportType?: T;
  startDate?: T;
  endDate?: T;
  accomplishmentsNarrative?: T;
  productsNarrative?: T;
  impactNarrative?: T;
  changesProblemsNarrative?: T;
  specialRequirementsNarrative?: T;
  reportNotes?: T;
  attachments?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reporting-snapshots_select".
 */
export interface ReportingSnapshotsSelect<T extends boolean = true> {
  label?: T;
  reportType?: T;
  reportingPeriod?: T;
  periodStart?: T;
  periodEnd?: T;
  filterScope?: T;
  metricPayload?: T;
  rpprPayload?: T;
  dataQualityPayload?: T;
  anomaliesPayload?: T;
  narrativeDrafts?: T;
  snapshotHash?: T;
  reproducibilityKey?: T;
  versionLabel?: T;
  createdBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reporting-audit-events_select".
 */
export interface ReportingAuditEventsSelect<T extends boolean = true> {
  eventType?: T;
  reportType?: T;
  reportingPeriod?: T;
  periodStart?: T;
  periodEnd?: T;
  filters?: T;
  exportType?: T;
  exportFormat?: T;
  metricKey?: T;
  snapshot?: T;
  notes?: T;
  createdBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reporting-saved-views_select".
 */
export interface ReportingSavedViewsSelect<T extends boolean = true> {
  label?: T;
  owner?: T;
  isShared?: T;
  reportType?: T;
  reportingPeriod?: T;
  startDate?: T;
  endDate?: T;
  filters?: T;
  metricKeys?:
    | T
    | {
        metricKey?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reporting-evidence-links_select".
 */
export interface ReportingEvidenceLinksSelect<T extends boolean = true> {
  title?: T;
  evidenceType?: T;
  rpprSection?: T;
  summary?: T;
  impactNote?: T;
  reportingPeriod?: T;
  linkedArtifacts?: T;
  linkedSnapshot?: T;
  linkedRpprReport?: T;
  occurredAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reporting-product-records_select".
 */
export interface ReportingProductRecordsSelect<T extends boolean = true> {
  title?: T;
  productType?: T;
  citation?: T;
  identifier?: T;
  url?: T;
  reportingPeriod?: T;
  linkedRpprReport?: T;
  linkedArtifacts?: T;
  reportedAt?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "accounts_select".
 */
export interface AccountsSelect<T extends boolean = true> {
  emailVerified?: T;
  emailVerifiedAt?: T;
  emailVerificationTokenHash?: T;
  emailVerificationExpiresAt?: T;
  role?: T;
  fullName?: T;
  currentStreak?: T;
  longestStreak?: T;
  lastStreakDate?: T;
  participantType?: T;
  projectRole?: T;
  organization?: T;
  organizationName?: T;
  contributionSummary?: T;
  participationStartDate?: T;
  participationEndDate?: T;
  firstGenCollegeStudent?: T;
  transferStudent?: T;
  includeInRppr?: T;
  ssoProvider?: T;
  ssoSubject?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  firstName?: T;
  lastName?: T;
  adminTheme?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "questions_select".
 */
export interface QuestionsSelect<T extends boolean = true> {
  user?: T;
  lesson?: T;
  chapter?: T;
  class?: T;
  status?: T;
  title?: T;
  body?: T;
  attachment?: T;
  answers?:
    | T
    | {
        author?: T;
        body?: T;
        createdAt?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quiz-questions_select".
 */
export interface QuizQuestionsSelect<T extends boolean = true> {
  title?: T;
  prompt?: T;
  options?:
    | T
    | {
        label?: T;
        isCorrect?: T;
        id?: T;
      };
  explanation?: T;
  attachments?: T;
  topic?: T;
  tags?: T;
  difficulty?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quizzes_select".
 */
export interface QuizzesSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  course?: T;
  chapter?: T;
  tags?: T;
  difficulty?: T;
  questions?: T;
  shuffleQuestions?: T;
  shuffleOptions?: T;
  scoring?: T;
  timeLimitSec?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quiz-attempts_select".
 */
export interface QuizAttemptsSelect<T extends boolean = true> {
  quiz?: T;
  lesson?: T;
  user?: T;
  startedAt?: T;
  completedAt?: T;
  durationSec?: T;
  questionOrder?:
    | T
    | {
        question?: T;
        id?: T;
      };
  answers?:
    | T
    | {
        question?: T;
        selectedOptionIds?:
          | T
          | {
              optionId?: T;
              id?: T;
            };
        optionOrder?:
          | T
          | {
              optionId?: T;
              id?: T;
            };
        isCorrect?: T;
        score?: T;
        id?: T;
      };
  score?: T;
  maxScore?: T;
  correctCount?: T;
  questionCount?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications_select".
 */
export interface NotificationsSelect<T extends boolean = true> {
  recipient?: T;
  type?: T;
  title?: T;
  body?: T;
  link?: T;
  question?: T;
  read?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lesson-progress_select".
 */
export interface LessonProgressSelect<T extends boolean = true> {
  user?: T;
  lesson?: T;
  chapter?: T;
  class?: T;
  completed?: T;
  completedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lesson-bookmarks_select".
 */
export interface LessonBookmarksSelect<T extends boolean = true> {
  user?: T;
  lesson?: T;
  chapter?: T;
  class?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "feedback_select".
 */
export interface FeedbackSelect<T extends boolean = true> {
  email?: T;
  read?: T;
  message?: T;
  pageUrl?: T;
  userAgent?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lesson-feedback_select".
 */
export interface LessonFeedbackSelect<T extends boolean = true> {
  user?: T;
  lesson?: T;
  chapter?: T;
  class?: T;
  rating?: T;
  message?: T;
  reply?: T;
  repliedAt?: T;
  repliedBy?: T;
  pageUrl?: T;
  userAgent?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Guidance content shown on the admin Help page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admin-help".
 */
export interface AdminHelp {
  id: number;
  title: string;
  subtitle?: string | null;
  /**
   * JSON array: [{ "label": string, "desc": string, "href": string }].
   */
  quickActions?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * JSON array of strings for topic tags.
   */
  topicChips?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * JSON array: [{ "question": string, "answer": string }].
   */
  faqs?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  supportEmail?: string | null;
  supportResponseTarget?: string | null;
  /**
   * Relative admin path or full URL.
   */
  supportRequestHref?: string | null;
  /**
   * JSON array: [{ "label": string, "desc": string, "href": string }].
   */
  resources?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  exploreLinks?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  resourcesLinks?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  connect?: {
    email?: string | null;
    /**
     * Use line breaks for multi-line addresses.
     */
    address?: string | null;
    externalLabel?: string | null;
    externalUrl?: string | null;
  };
  feedback?: {
    enabled?: boolean | null;
    title?: string | null;
    description?: string | null;
    buttonLabel?: string | null;
  };
  bottom: {
    /**
     * Use {year} to insert the current year.
     */
    copyrightLine?: string | null;
    subLine?: string | null;
    nsfCompliance: {
      /**
       * When enabled, NSF compliance text appears in the global site footer.
       */
      enabled?: boolean | null;
      fundingAcknowledgment: string;
      disclaimer: string;
    };
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Controls branding assets used on the student-facing site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-branding".
 */
export interface SiteBranding {
  id: number;
  /**
   * Shown on the student home page and used as the browser tab icon (favicon).
   */
  programLogo?: (number | null) | Media;
  /**
   * Accessible description for the uploaded program logo.
   */
  programLogoAlt?: string | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admin-help_select".
 */
export interface AdminHelpSelect<T extends boolean = true> {
  title?: T;
  subtitle?: T;
  quickActions?: T;
  topicChips?: T;
  faqs?: T;
  supportEmail?: T;
  supportResponseTarget?: T;
  supportRequestHref?: T;
  resources?: T;
  body?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  exploreLinks?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  resourcesLinks?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  connect?:
    | T
    | {
        email?: T;
        address?: T;
        externalLabel?: T;
        externalUrl?: T;
      };
  feedback?:
    | T
    | {
        enabled?: T;
        title?: T;
        description?: T;
        buttonLabel?: T;
      };
  bottom?:
    | T
    | {
        copyrightLine?: T;
        subLine?: T;
        nsfCompliance?:
          | T
          | {
              enabled?: T;
              fundingAcknowledgment?: T;
              disclaimer?: T;
            };
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-branding_select".
 */
export interface SiteBrandingSelect<T extends boolean = true> {
  programLogo?: T;
  programLogoAlt?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}