import React from 'react'
import { Document, Page, StyleSheet, Text, View } from '@react-pdf/renderer'

type RpprReportDocumentProps = {
  meta: {
    reportType: string
    periodStart: string
    periodEnd: string
    awardNumber?: string | null
    projectTitle?: string | null
  }
  sections: Record<string, string>
  metrics: Record<string, unknown>
  includeDataAppendix?: boolean
  generatedAt: string
}

const styles = StyleSheet.create({
  page: {
    padding: 40,
    fontFamily: 'Helvetica',
    fontSize: 12,
    color: '#111827',
  },
  coverTitle: {
    fontSize: 24,
    marginBottom: 10,
    color: '#0066CC',
    fontFamily: 'Helvetica-Bold',
  },
  sectionTitle: {
    fontSize: 16,
    marginBottom: 8,
    color: '#0066CC',
    fontFamily: 'Helvetica-Bold',
  },
  paragraph: {
    lineHeight: 1.5,
    marginBottom: 10,
  },
  tableRow: {
    flexDirection: 'row',
    borderBottomWidth: 1,
    borderBottomColor: '#E5E7EB',
    paddingVertical: 4,
  },
  tableCellLabel: {
    width: '45%',
    fontFamily: 'Helvetica-Bold',
  },
  tableCellValue: {
    width: '55%',
  },
  footer: {
    position: 'absolute',
    left: 40,
    right: 40,
    bottom: 20,
    fontSize: 10,
    color: '#4B5563',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
})

const sectionEntries: Array<{ key: string; title: string }> = [
  { key: 'accomplishments', title: 'Accomplishments' },
  { key: 'products', title: 'Products' },
  { key: 'participantsOrganizations', title: 'Participants & Organizations' },
  { key: 'impact', title: 'Impact' },
  { key: 'changesProblems', title: 'Changes/Problems' },
  { key: 'specialRequirements', title: 'Special Requirements' },
]

const Footer = ({ generatedAt }: { generatedAt: string }) => (
  <View style={styles.footer} fixed>
    <Text>Generated by NSF CURE SBP Platform</Text>
    <Text render={({ pageNumber, totalPages }) => `Page ${pageNumber} of ${totalPages}`} />
    <Text>{new Date(generatedAt).toISOString().slice(0, 10)}</Text>
  </View>
)

const MetricsRows = ({ metrics }: { metrics: Record<string, unknown> }) => {
  const entries = Object.entries(metrics).slice(0, 18)
  if (!entries.length) return null
  return (
    <View>
      {entries.map(([key, value]) => (
        <View key={key} style={styles.tableRow}>
          <Text style={styles.tableCellLabel}>{key}</Text>
          <Text style={styles.tableCellValue}>
            {typeof value === 'object' ? JSON.stringify(value) : String(value ?? '')}
          </Text>
        </View>
      ))}
    </View>
  )
}

export const RpprReportDocument = ({
  meta,
  sections,
  metrics,
  includeDataAppendix = false,
  generatedAt,
}: RpprReportDocumentProps) => (
  <Document>
    <Page size="A4" style={styles.page}>
      <Text style={styles.coverTitle}>NSF RPPR Annual Report</Text>
      <Text style={styles.paragraph}>Project: {meta.projectTitle || 'NSF CURE SBP'}</Text>
      <Text style={styles.paragraph}>Award Number: {meta.awardNumber || 'N/A'}</Text>
      <Text style={styles.paragraph}>Report Type: {meta.reportType}</Text>
      <Text style={styles.paragraph}>
        Reporting Period: {meta.periodStart} to {meta.periodEnd}
      </Text>
      <Text style={styles.paragraph}>
        Generated: {new Date(generatedAt).toLocaleString('en-US', { timeZone: 'UTC' })}
      </Text>
      <Footer generatedAt={generatedAt} />
    </Page>

    {sectionEntries.map((section) => (
      <Page key={section.key} size="A4" style={styles.page}>
        <Text style={styles.sectionTitle}>{section.title}</Text>
        <Text style={styles.paragraph}>{sections[section.key] || 'No narrative provided.'}</Text>
        <Text style={[styles.sectionTitle, { fontSize: 13, marginTop: 8 }]}>Key Metrics</Text>
        <MetricsRows
          metrics={
            typeof metrics[section.key] === 'object' && metrics[section.key] !== null
              ? (metrics[section.key] as Record<string, unknown>)
              : {}
          }
        />
        <Footer generatedAt={generatedAt} />
      </Page>
    ))}

    {includeDataAppendix ? (
      <Page size="A4" style={styles.page}>
        <Text style={styles.sectionTitle}>Data Appendix</Text>
        <MetricsRows metrics={metrics} />
        <Footer generatedAt={generatedAt} />
      </Page>
    ) : null}
  </Document>
)
